# config file version


# list of data sources to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: monitor_DurationModel
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'